### ISSUE TITLE
can't open file ./diffuse.tga

### ISSUE THREAD

**Issue by Weizihan** [TomSavas/simpletons-renderer#1]
hello,After i 'make' this project and run the './renderer'。
terminal show me 
```
can't open file ./diffuse.tga
can't open file ./nm_tangent.tga
```
how to get these file?

**Comment by TomSavas** [comment]
Hello,
Grab the diablo demon model from [here](https://github.com/ssloy/tinyrenderer/tree/master/obj/diablo3_pose). Place all of the files next to the binary (wherever your `renderer` executable is) and rename (or do a symlink) as follows:
- diablo3_pose.obj -> model.obj
- diablo3_pose_diffuse.tga -> diffuse.tga
- diablo3_pose_nm_tangent.tga -> nm_tangent.tga

Alternatively you can just change the hard-coded strings in the code and recompile.

Actually, this should work with any obj file and diffuse/tangent space normal textures in tga format. If you have any of those you can rename these files in the way I described above and it should still work! As a matter of fact any model from [here](https://github.com/ssloy/tinyrenderer/tree/master/obj) should work I believe.

Couple of notes, as I suspect you might have issues with this. You _need_ to be running this in a TTY where xserver / wayland / etc. is not running, otherwise you will not see any input! To switch to a different TTY than your xserver is running on try Ctrl + Alt + F1 (if F1 doesn't work try some other F keys). From there on you continue as usual. Make sure you are adding sudo -- `sudo ./renderer` -- the renderer needs access to fb0 file which is under superuser permissions usually.

**Comment by Weizihan** [comment]
i have succeed run the ./renderer with your help,thanks so much.i'll try my best to understand how to write a render and improve my english skill :D

**Comment by TomSavas** [comment]
No worries. Best of luck!
